### PR TITLE
Fixes cursor iteration for set_union

### PR DESCRIPTION
**Pull request by jwest591**
last() must return a cursor with cursor_type::second otherwise comparing against a cursor obtained via successive inc() calls fails.

This change also allows flux::to work with set_union.

### CODE REVIEW

**Review by tcbrindle — APPROVED** [review]

**Comment by tcbrindle** [comment]
Hi @jwest591, thanks for the PR, and in particular for all the test additions, it looks great.

@jnytra, `set_union` was yours originally, are you happy to merge?

**Comment by tcbrindle** [comment]
@jnytra I'm going to merge this as I think the fix is good, let me know if you see any problems

**Comment by tcbrindle** [comment]
Merged, thanks very much @jwest591

**Comment by jwest591** [comment]
You're welcome!  Glad it was useful.

**Comment by jnytra** [comment]
Thanks for the fix @jwest591, it also looks good for me @tcbrindle. :-)

**Pull request merged**
